=== TracerBench/tracerbench/packages/cli/tb-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": {
    },
    "definitions": {
        "IBenchmarkEnvironmentOverride": {
            "additionalProperties": {
            },
            "properties": {
                "cpuThrottle": {
                    "type": "number"
                },
                "emulateDevice": {
                    "type": "string"
                },
                "emulateDeviceOrientation": {
                    "type": "string"
                },
                "network": {
                    "type": [
                        "string",
                        "number"
                    ]
                }
            },
            "type": "object"
        },
        "IHARServer": {
            "properties": {
                "dist": {
                    "type": "string"
                },
                "har": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "socksPort": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "IMarker": {
            "properties": {
                "label": {
                    "description": "Label of phase",
                    "type": "string"
                },
                "start": {
                    "description": "performance.mark name",
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "appName": {
            "type": "string"
        },
        "browserArgs": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "controlBenchmarkEnvironment": {
            "$ref": "#/definitions/IBenchmarkEnvironmentOverride"
        },
        "controlURL": {
            "type": "string"
        },
        "cookiespath": {
            "type": "string"
        },
        "cpuThrottleRate": {
            "type": [
                "string",
                "number"
            ]
        },
        "debug": {
            "type": "boolean"
        },
        "emulateDevice": {
            "type": "string"
        },
        "emulateDeviceOrientation": {
            "type": "string"
        },
        "event": {
            "type": "string"
        },
        "experimentBenchmarkEnvironment": {
            "$ref": "#/definitions/IBenchmarkEnvironmentOverride"
        },
        "experimentURL": {
            "type": "string"
        },
        "extends": {
            "type": "string"
        },
        "fidelity": {
            "anyOf": [
                {
                    "enum": [
                        "high",
                        "low",
                        "medium",
                        "test"
                    ],
                    "type": "string"
                },
                {
                    "type": "number"
                }
            ]
        },
        "filter": {
            "type": "string"
        },
        "headless": {
            "type": "boolean"
        },
        "inputFilePath": {
            "type": "string"
        },
        "isCIEnv": {
            "type": [
                "string",
                "boolean"
            ]
        },
        "locations": {
            "type": "string"
        },
        "marker": {
            "type": "string"
        },
        "markers": {
            "anyOf": [
                {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                {
                    "items": {
                        "$ref": "#/definitions/IMarker"
                    },
                    "type": "array"
                },
                {
                    "items": {
                        "enum": [
                            "connectEnd",
                            "connectStart",
                            "decodedBodySize",
                            "domComplete",
                            "domContentLoadedEventEnd",
                            "domContentLoadedEventStart",
                            "domInteractive",
                            "domainLookupEnd",
                            "domainLookupStart",
                            "duration",
                            "encodedBodySize",
                            "entryType",
                            "fetchStart",
                            "initiatorType",
                            "loadEventEnd",
                            "loadEventStart",
                            "name",
                            "nextHopProtocol",
                            "redirectCount",
                            "redirectEnd",
                            "redirectStart",
                            "requestStart",
                            "responseEnd",
                            "responseStart",
                            "secureConnectionStart",
                            "startTime",
                            "toJSON",
                            "transferSize",
                            "type",
                            "unloadEventEnd",
                            "unloadEventStart",
                            "workerStart"
                        ],
                        "type": "string"
                    },
                    "type": "array"
                },
                {
                    "type": "string"
                }
            ]
        },
        "methods": {
            "type": "string"
        },
        "network": {
            "type": [
                "string",
                "number"
            ]
        },
        "outputFilePath": {
            "type": "string"
        },
        "plotTitle": {
            "type": "string"
        },
        "regressionThreshold": {
            "type": [
                "string",
                "number"
            ]
        },
        "report": {
            "type": "string"
        },
        "runtimeStats": {
            "type": "boolean"
        },
        "servers": {
            "additionalItems": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/IHARServer"
                    },
                    {
                        "$ref": "#/definitions/IHARServer"
                    }
                ]
            },
            "items": [
                {
                    "$ref": "#/definitions/IHARServer"
                },
                {
                    "$ref": "#/definitions/IHARServer"
                }
            ],
            "minItems": 2,
            "type": "array"
        },
        "socksPorts": {
            "additionalItems": {
                "anyOf": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "number"
                    }
                ]
            },
            "items": [
                {
                    "type": "number"
                },
                {
                    "type": "number"
                }
            ],
            "minItems": 2,
            "type": "array"
        },
        "tbResultsFolder": {
            "type": "string"
        },
        "traceFrame": {
            "type": "string"
        },
        "tracingLocationSearch": {
            "type": "string"
        },
        "url": {
            "type": "string"
        }
    },
    "type": "object"
}

=== TracerBench/tracerbench/packages/cli/test/fixtures/release/tbconfig.json
{
  "$schema": "https://raw.githubusercontent.com/TracerBench/tracerbench/master/packages/cli/tb-schema.json",
  "extends": "../../tbconfig_base.json",
  "plotTitle": "fixtures release",
  "regressionThreshold": "50",
  "fidelity": "medium",
  "controlURL": "file:///Users/malynch/D/tracerbench/packages/cli/test/fixtures/release/index.html",
  "experimentURL": "file:///Users/malynch/D/tracerbench/packages/cli/test/fixtures/release/index.html"
}
